FROM ruby:2.5
RUN apt-get update
RUN apt-get install -y \ 
  build-essential \
  libpq-dev \
  nodejs \
  postgresql-client \
  yarn

WORKDIR /cooklog
COPY Gemfile Gemfile.lock /cooklog/
RUN bundle install
COPY . .
CMD ["rails", "s", "-b", "0.0.0.0"]